packages:
  - packages/*
  - examples/*
  - registry/software/*
  - registry/agent/*
  - registry/file-system/*
  - registry/tool/*

ignoredBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - browser-tabs-lock
  - core-js

onlyBuiltDependencies:
  - '@biomejs/biome'
  - better-sqlite3
  - bun
  - cbor-extract
  - esbuild
  - lefthook
  - sharp

patchedDependencies:
  '@secure-exec/nodejs@0.2.1': patches/@secure-exec__nodejs@0.2.1.patch
  '@secure-exec/v8@0.2.1': patches/@secure-exec__v8@0.2.1.patch
